### PR TITLE
Code quality increased.

### LINKED ISSUE #38: Improving the code quality from Codacy from grade B to A.
**Is your feature request related to a problem? Please describe.**
Improving the code quality from Codacy from grade B to A.

**Describe the solution you'd like**
Solving some issues like markdown guidelines, unexpected errors in syntax etc. to improve code quality.

### PR DESCRIPTION
**Pull request by garimasingh128**
## Issue that this pull request solves

 Closes: #38

## Proposed changes

Brief description of what is fixed or changed
- Github Markdown errors solved
- Filenames changed
- Spelling errors solved

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update (Documentation content changed)
- [x] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

@xlogix kindly review.

### CODE REVIEW

**Comment by xlogix** [comment]
Why closed it?

**Comment by xlogix** [comment]
@garimasingh128 Thanks for the PR and welcome to Footsteps Project. There are still have some issues left in the PR Quality review. Are you gonna work on those?

**Comment by garimasingh128** [comment]
Yes sir, I'll take 1-2 days more. That's why I closed it now.

**Comment by xlogix** [comment]
Okay. I know you sent another PR for this but for future reference, I just wanna say that you can keep committing on your repo and they will be automatically updated on the PR. 
A good way to raise PRs is to maintain a branch for every feature you're adding... That way any commit on that branch will automatically be added to the PR and your master branch will be available for other work.

**Pull request closed without merging**
