### PR TITLE
Code quality increase.

### LINKED ISSUE #38: Improving the code quality from Codacy from grade B to A.
**Is your feature request related to a problem? Please describe.**
Improving the code quality from Codacy from grade B to A.

**Describe the solution you'd like**
Solving some issues like markdown guidelines, unexpected errors in syntax etc. to improve code quality.

### PR DESCRIPTION
**Pull request by garimasingh128**
## Issue that this pull request solves

 Closes: #38

## Proposed changes

Brief description of what is fixed or changed
- Github Markdown errors solved
- some Filenames changed
- Spelling errors solved
- JS bugs fixed

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update (Documentation content changed)
- [x] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

@xlogix kindly review.

### CODE REVIEW

**Comment by xlogix** [comment]
There are still some issues in the Quality review... Are you gonna work on it? Just commit on your repo and the PR would automatically be updated...

**Comment by garimasingh128** [comment]
No sir, I did my work. I ignored some issues like file name changes and all.

**Comment by xlogix** [comment]
There are still more issues in indents in the code_of_conduct file
https://app.codacy.com/manual/fnplus/footsteps-extension/pullRequest?prid=5347871

**Comment by garimasingh128** [comment]
@xlogix  sir I made some changes. Kindly review it once again.

**Comment by xlogix** [comment]
Merged!

**Pull request merged**
