### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by Riyagoel2**

### CODE REVIEW

**Comment by xlogix** [comment]
Can you resolve the errors @Riyagoel2?

**Comment by Riyagoel2** [comment]
Yes but I am not able to understand the space issue
Can you please help

**Comment by xlogix** [comment]
@Riyagoel2 The errors are happening because of improper indents of the tick `. The ticks are used to specify the language but they don't actually show up in the readme...Instead, Github renders it as a block of code...

Also, can you add the installation instructions/link for installing node?

**Comment by Riyagoel2** [comment]
Ok , I'll add instructions for installing node

**Comment by xlogix** [comment]
> Ok , I'll add instructions for installing node

I'll merge the PR when you do.

**Review by xlogix — CHANGES_REQUESTED** [review]
The Link to the Node Installation isn't right!

**Comment by Riyagoel2** [comment]
Why was I unassigned?

**Comment by xlogix** [comment]
@Riyagoel2 I had managed to fix the issues so I didn't think it was required. It won't affect your points

**Comment by Riyagoel2** [comment]
Ok Thanks!

**Pull request merged**
